// old-fashioned-react/src/App.tsx
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { lazy, Suspense } from "react";

const VictoryScreen = lazy(() => import("./pages/VictoryScreen"));
const HigherLower = lazy(() => import("./pages/HigherLower"));

const App = () => {
  return (
    <BrowserRouter>
      <Routes>
        <Route
          path="/"
          element={
            <Suspense fallback={<h1>Loading</h1>}>
              <HigherLower />
            </Suspense>
          }
        />
        <Route
          path="/victory"
          element={
            <Suspense fallback={<h1>Loading</h1>}>
              <VictoryScreen />
            </Suspense>
          }
        />
        <Route path="*" element={<h1>404 not found</h1>} />
      </Routes>
    </BrowserRouter>
  );
};

export default App;

// new-fashioned-solid/src/App.tsx
import { lazy, Suspense } from "solid-js";
import { Routes, Route, Router } from "@solidjs/router";

const VictoryScreen = lazy(() => import("./pages/VictoryScreen"));
const HigherLower = lazy(() => import("./pages/HigherLower"));

const App = () => {
  return (
    <Router>
      <Routes>
        <Route path="/" component={HigherLower} />
        <Route path="/victory" component={VictoryScreen} />
        <Route path="*" component={() => <h1>404 not found</h1>} />
      </Routes>
    </Router>
  );
};

export default App;
